[tasks.prepare-build-dir]
command = "mkdir"
args = ["-p", "build"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-linux]
command = "cross"
args = ["build", "--target=x86_64-unknown-linux-gnu", "--release"]

[tasks.pack-linux]
dependencies = ["build-linux"]
command = "mv"
args = ["target/x86_64-unknown-linux-gnu/release/foucault", "build/x86_64-unknown-linux-gnu"]

[tasks.build-pc]
command = "cross"
args = ["build", "--target=x86_64-pc-windows-gnu", "--release"]

[tasks.pack-pc]
dependencies = ["build-pc"]
command = "mv"
args = ["target/x86_64-pc-windows-gnu/release/foucault.exe", "build/x86_64-pc-windows-gnu.exe"]

[tasks.build-all]
dependencies = ["clean", "build-linux", "build-pc"]

[tasks.pack-all]
dependencies = ["clean", "prepare-build-dir", "pack-linux", "pack-pc"]
