name: Prepare release
on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-unknown-linux-gnu
        path: target/release/foucault

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-pc-windows-mscv.exe
        path: target/release/foucault.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: target/release/foucault

  prepare-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-pc-windows-mscv.exe
      - uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin

      - name: Prepare release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            x86_64-unknown-linux-gnu
            x86_64-pc-windows-mscv.exe
            x86_64-apple-darwin
