name: Prepare release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Rename binarie
      run: mv target/release/foucault foucault-x86_64-unknown-linux-gnu
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: foucault-x86_64-unknown-linux-gnu
        path: foucault-x86_64-unknown-linux-gnu

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Rename binarie
      shell: bash
      run: mv target/release/foucault.exe foucault-x86_64-pc-windows-mscv.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: foucault-x86_64-pc-windows-mscv
        path: foucault-x86_64-pc-windows-mscv.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Rename binarie
        run: mv target/release/foucault foucault-x86_64-apple-darwin
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: foucault-x86_64-apple-darwin
          path: foucault-x86_64-apple-darwin

  prepare-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foucault-x86_64-unknown-linux-gnu
      - uses: actions/download-artifact@v4
        with:
          name: foucault-x86_64-pc-windows-mscv
      - uses: actions/download-artifact@v4
        with:
          name: foucault-x86_64-apple-darwin

      - name: Prepare release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            foucault-x86_64-unknown-linux-gnu
            foucault-x86_64-pc-windows-mscv
            foucault-x86_64-apple-darwin
